name: "Deploy ML Flow"

on:
  workflow_dispatch:

jobs:
  deploy-ml-services:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Influx, MQTT, Telegraf and Grafana
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          docker login 
          
          cat > compose.env <<EOF
          TRAEFIK_DOMAIN=urbanairlab.hn
          INFLUX_URL="${{ secrets.INFLUX_URL }}"
          INFLUX_ORG="${{ secrets.INFLUX_ORG }}"
          DOCKER_INFLUXDB_INIT_USERNAME="${{ secrets.DOCKER_INFLUXDB_INIT_USERNAME }}"
          DOCKER_INFLUXDB_INIT_PASSWORD="${{ secrets.DOCKER_INFLUXDB_INIT_PASSWORD }}"
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="${{ secrets.DOCKER_INFLUXDB_INIT_ADMIN_TOKEN }}"
          
          GF_SECURITY_ADMIN_USER="${{ secrets.GF_SECURITY_ADMIN_USER }}"
          GF_SECURITY_ADMIN_PASSWORD="${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}"
          
          LUBW_USERNAME="${{ secrets.LUBW_USERNAME }}"
          LUBW_PASSWORD="${{ secrets.LUBW_PASSWORD }}"
          LUBW_BASE_URL="${{ secrets.LUBW_BASE_URL }}"
          
          MQTT_USERNAME="${{ secrets.MQTT_USERNAME }}"
          MQTT_PASSWORD="${{ secrets.MQTT_PASSWORD }}"
          MQTT_SERVER="${{ secrets.MQTT_SERVER }}"
          MQTT_PORT="${{ secrets.MQTT_PORT }}"
          
          HHN_FORWARD_USERNAME="${{ secrets.HHN_FORWARD_USERNAME }}"
          HHN_FORWARD_PASSWORD="${{ secrets.HHN_FORWARD_PASSWORD }}"
          EOF
          
          cat compose.env
          
          docker -H ssh://root@urbanairlab.hn compose -p ual_infrastructure_deployments  -f docker-compose.yaml rm -f -s -v
          docker -H ssh://root@urbanairlab.hn compose -p ual_infrastructure_deployments  -f docker-compose.yaml --env-file compose.env up -d --pull always
          
          
